import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sm:bg-[url('../public/bgfull.png')] bg-[url('../public/bgmobile.png')] h-full bg-no-repeat bg-cover bg-center">
        <Navbar/>
        {children}
        </div>
        </body>
    </html>
  );
}
